### ISSUE TITLE
Code blocks are difficult to read, at least on Firefox

### ISSUE THREAD

**Issue by robertgr991** [ncthbrt/nact.io#33]
Hello,

Code blocks are rather difficult to read, especially on Firefox(78.0.2). Here is a screen capture(I've included normal text to show the contrast):

![capture_nact_1](https://user-images.githubusercontent.com/36689800/87453177-d1cbfa00-c60a-11ea-9711-4628f93949fb.PNG)

On Chrome they are a little more readable(perhaps Firefox interprets that font a little different), but still looks like the font size is too small.

I suggest adding a `font-size: 1.15rem` for code blocks, this way you can easily read them. Here is a screen capture with this change applied(Firefox):

![capture_nact_3](https://user-images.githubusercontent.com/36689800/87453571-5585e680-c60b-11ea-8891-cb8052b91a26.PNG)

**Comment by ncthbrt** [comment]
Hi @robertgr991 
Thanks for the feedback.

**Comment by ncthbrt** [comment]
I've updated the styling. Just need to do a deploy

**Comment by ncthbrt** [comment]
Deployed. Thanks @robertgr991
